# Generated by Django 3.1.1 on 2020-11-09 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('Categoria_id', models.AutoField(primary_key=True, serialize=False, verbose_name='idCategoria')),
                ('nombrecategoria', models.CharField(max_length=40, verbose_name='NombreCategoria')),
            ],
        ),
        migrations.CreateModel(
            name='Editor',
            fields=[
                ('rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='Rut')),
                ('nombre', models.CharField(max_length=50, verbose_name='nombreeditor')),
                ('telefono', models.IntegerField(verbose_name='numeroeditor')),
            ],
        ),
        migrations.CreateModel(
            name='Ilustracion',
            fields=[
                ('Ilustracion_id', models.AutoField(primary_key=True, serialize=False, verbose_name='idIlustracion')),
                ('Tipoymodelo', models.CharField(max_length=100, verbose_name='Tipoymodelo')),
                ('Editor', models.CharField(max_length=60, verbose_name='Editor')),
                ('fecha', models.DateField(verbose_name='fechaVehiculo')),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('Imagen_id', models.AutoField(primary_key=True, serialize=False, verbose_name='idImagen')),
                ('Ilustracion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Ilustracion')),
            ],
        ),
    ]
